"use client";
import Link from "next/link";
import {useCommerce} from "@/lib/commerce-context";
export default function SiteFooter(){
 const{settings}=useCommerce();
 const phone=settings.phone||"+962 79 727 2110",email=settings.email||"dar_shan.a@hotmail.com";
 const wa=(settings.whatsapp||"+962797272110").replace(/\D/g,"");
 const facebook=settings.facebookUrl||"https://www.facebook.com/",instagram=settings.instagramUrl||"https://www.instagram.com/";
 return <footer className="bg-ink text-gray-300 mt-16"><div className="max-w-6xl mx-auto px-6 md:px-12 py-12 grid sm:grid-cols-2 lg:grid-cols-4 gap-9 text-sm"><div><div className="flex items-center gap-3 mb-4"><span className="w-12 h-12 rounded-lg overflow-hidden bg-white"><img src="/dar-shaan-logo.png" alt="شعار دار شأن" className="w-full h-full object-cover"/></span><b className="text-white text-xl">دار شأن</b></div><p className="leading-7 text-gray-400">دار نشر وتوزيع عربية، نختار الكتب التي تستحق وقت القارئ وتترك أثرًا.</p></div><div><h3 className="text-white font-extrabold mb-4">روابط مهمة</h3><Link className="block mb-2 hover:text-white" href="/">الرئيسية</Link><Link className="block mb-2 hover:text-white" href="/categories">جميع الكتب</Link><Link className="block mb-2 hover:text-white" href="/about">عن الدار والأسئلة الشائعة</Link><Link className="block hover:text-white" href="/favorites">المفضلة</Link></div><div><h3 className="text-white font-extrabold mb-4">معلومات التواصل</h3><a href={`tel:${phone.replace(/\s/g,"")}`} className="block mb-3 hover:text-white"><span className="text-white">الهاتف:</span> <bdi dir="ltr">{phone}</bdi></a><a href={`mailto:${email}`} className="block mb-3 hover:text-white"><span className="text-white">البريد:</span> <bdi dir="ltr">{email}</bdi></a><p><span className="text-white">العنوان:</span> {settings.address||"عمّان، الأردن"}</p></div><div className="text-center"><h3 className="text-white font-extrabold mb-4">تابعونا وتواصل معنا</h3><div className="flex justify-center gap-3 mb-6" dir="ltr"><Social href={facebook} label="فيسبوك" brand="facebook"/><Social href={instagram} label="إنستغرام" brand="instagram"/><Social href={`https://wa.me/${wa}`} label="واتساب" brand="whatsapp"/></div><h4 className="text-white font-extrabold mb-1">ساعات العمل</h4><p className="text-sm text-gray-400" dir="ltr">{settings.workingHours||"10:00–19:00"}</p></div></div><div className="border-t border-white/10 text-center text-gray-500 py-5 text-xs">دار شأن للنشر والتوزيع © {new Date().getFullYear()} — جميع الحقوق محفوظة</div></footer>
}
type Brand="facebook"|"instagram"|"whatsapp";
function Social({href,label,brand}:{href:string;label:string;brand:Brand}){const bg=brand==="facebook"?"bg-[#1877F2]":brand==="whatsapp"?"bg-[#25D366]":"instagram-gradient";return <a href={href} target="_blank" rel="noreferrer" aria-label={label} title={label} className={`social-icon w-12 h-12 rounded-full text-white grid place-items-center shadow-lg hover:-translate-y-1 ${bg}`}><BrandIcon brand={brand}/></a>}
function BrandIcon({brand}:{brand:Brand}){if(brand==="facebook")return <svg viewBox="0 0 24 24" className="w-6 h-6 fill-current" aria-hidden="true"><path d="M13.7 22v-8h2.7l.4-3.1h-3.1v-2c0-.9.3-1.5 1.6-1.5H17V4.6c-.3 0-1.3-.1-2.5-.1-2.5 0-4.2 1.5-4.2 4.3v2.1H7.5V14h2.8v8h3.4Z"/></svg>;if(brand==="instagram")return <svg viewBox="0 0 24 24" className="w-6 h-6 fill-none stroke-current" strokeWidth="2" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" className="fill-current stroke-0"/></svg>;return <svg viewBox="0 0 24 24" className="w-7 h-7 fill-current" aria-hidden="true"><path d="M12 2a9.8 9.8 0 0 0-8.4 14.9L2.2 22l5.2-1.4A10 10 0 1 0 12 2Zm0 17.9a8 8 0 0 1-4.1-1.1l-.3-.2-3.1.8.8-3-.2-.3A8 8 0 1 1 12 20Zm4.4-6c-.2-.1-1.4-.7-1.7-.8-.2-.1-.4-.1-.6.1l-.8 1c-.1.2-.3.2-.5.1-1.4-.7-2.4-1.3-3.3-2.9-.2-.3.2-.5.6-1 .1-.2.1-.4 0-.6l-.7-1.7c-.2-.4-.4-.4-.6-.4h-.5c-.2 0-.5.1-.7.3-.3.3-1 1-1 2.4s1 2.8 1.2 3c.1.2 2 3.1 5 4.2 1.8.6 2.5.6 3.4.5 1-.1 1.5-.7 1.7-1.3.2-.6.2-1.1.1-1.3-.2-.2-.4-.3-.6-.4Z"/></svg>}
