"use client";
import {createContext,useContext,useEffect,useState,ReactNode} from "react";
import {supabase} from "./supabase";
import {uploadBookCover} from "./book-covers";
export type Book={id:string;title:string;author:string;category:string;price:number;stock:number;description:string;isbn:string;pages:number;cover?:string;publisher?:string;discountPrice?:number;lowStock?:number};
export type Order={id:string;userId:string;customer:string;phone:string;address:string;items:{id:string;title:string;qty:number;price:number}[];total:number;status:string;date:string};
const seed:Book[]=[{id:"1",title:"ليالي الشام",author:"أحمد الزهراني",category:"روايات",price:12.5,stock:84,description:"رواية تتقفّى أثر مدينة تتغيّر ملامحها مع كل جيل.",isbn:"978-9957-00-001-7",pages:328},{id:"2",title:"ظلال المعنى",author:"سلمى قاسم",category:"فكر وفلسفة",price:9.9,stock:5,description:"تأملات في اللغة والمعنى.",isbn:"978-9957-00-002-4",pages:216},{id:"3",title:"في حضرة الكلمة",author:"يوسف النابلسي",category:"فكر وفلسفة",price:14,stock:40,description:"رحلة أدبية في أثر الكلمة.",isbn:"978-9957-00-003-1",pages:280}];
type Store={books:Book[];orders:Order[];ready:boolean;cloudReady:boolean;error:string;addBook:(b:Omit<Book,"id">)=>void;updateBook:(id:string,b:Partial<Book>)=>void;removeBook:(id:string)=>void;createOrder:(o:Omit<Order,"id"|"status"|"date">)=>Order;updateOrderStatus:(id:string,status:string)=>void;migrateLocalBooks:()=>Promise<number>};
const C=createContext<Store|null>(null);
const bookFromDb=(b:any):Book=>({id:b.id,title:b.title,author:b.author,category:b.category,price:Number(b.price),stock:b.stock,description:b.description||"",isbn:b.isbn||"",pages:b.pages||0,cover:b.cover_url||undefined,publisher:b.publisher||undefined,discountPrice:b.discount_price==null?undefined:Number(b.discount_price),lowStock:b.low_stock});
const bookToDb=(b:Omit<Book,"id">)=>({title:b.title,author:b.author,category:b.category,price:b.price,stock:b.stock,description:b.description,isbn:b.isbn,pages:b.pages,cover_url:b.cover||null,publisher:b.publisher||"",discount_price:b.discountPrice||null,low_stock:b.lowStock??10,is_published:true});
const orderFromDb=(o:any):Order=>({id:o.id,userId:o.user_id,customer:o.customer,phone:o.phone,address:o.address,total:Number(o.total),status:o.status,date:new Date(o.created_at).toLocaleDateString("en-GB"),items:(o.order_items||[]).map((i:any)=>({id:i.book_id||i.id,title:i.title,qty:i.quantity,price:Number(i.price)}))});
export function StoreProvider({children}:{children:ReactNode}){
 const[books,setBooks]=useState<Book[]>(seed),[orders,setOrders]=useState<Order[]>([]),[ready,setReady]=useState(false),[cloudReady,setCloudReady]=useState(false),[error,setError]=useState("");
 const load=async()=>{const[b,o]=await Promise.all([supabase.from("books").select("*").eq("is_published",true).order("created_at",{ascending:false}),supabase.from("orders").select("*,order_items(*)").order("created_at",{ascending:false})]);const local=JSON.parse(localStorage.getItem("darshan-books")||"null");if(b.error){setBooks(local||seed);setError("تعذر الاتصال مؤقتًا بقاعدة البيانات");setCloudReady(false)}else{const cloud=(b.data||[]).map(bookFromDb);setBooks(cloud.length?cloud:(local||seed));setCloudReady(true);setError("")}if(!o.error)setOrders((o.data||[]).map(orderFromDb));setReady(true)};
 useEffect(()=>{load();const{data}=supabase.auth.onAuthStateChange(()=>setTimeout(load,0));return()=>data.subscription.unsubscribe()},[]);
 const addBook=(b:Omit<Book,"id">)=>{const temp={...b,id:crypto.randomUUID()};setBooks(x=>[temp,...x]);supabase.from("books").insert({...bookToDb(b),id:temp.id}).then(({error})=>{if(error){setBooks(x=>x.filter(v=>v.id!==temp.id));setError("تعذر حفظ الكتاب: "+error.message)}})};
 const updateBook=(id:string,b:Partial<Book>)=>{setBooks(x=>x.map(v=>v.id===id?{...v,...b}:v));const patch:any={};if(b.title!==undefined)patch.title=b.title;if(b.author!==undefined)patch.author=b.author;if(b.category!==undefined)patch.category=b.category;if(b.price!==undefined)patch.price=b.price;if(b.stock!==undefined)patch.stock=b.stock;if(b.description!==undefined)patch.description=b.description;if(b.isbn!==undefined)patch.isbn=b.isbn;if(b.pages!==undefined)patch.pages=b.pages;if(b.cover!==undefined)patch.cover_url=b.cover||null;if(b.publisher!==undefined)patch.publisher=b.publisher;if(b.discountPrice!==undefined)patch.discount_price=b.discountPrice||null;if(b.lowStock!==undefined)patch.low_stock=b.lowStock;supabase.from("books").update(patch).eq("id",id).then(({error})=>{if(error)setError("تعذر حفظ التعديل: "+error.message)})};
 const removeBook=(id:string)=>{const old=books.find(v=>v.id===id);setBooks(x=>x.filter(v=>v.id!==id));supabase.from("books").delete().eq("id",id).then(({error})=>{if(error&&old){setBooks(x=>[old,...x]);setError("تعذر حذف الكتاب: "+error.message)}})};
 const createOrder=(o:Omit<Order,"id"|"status"|"date">)=>{const created:Order={...o,id:crypto.randomUUID(),status:"قيد التجهيز",date:new Date().toLocaleDateString("en-GB")};setOrders(x=>[created,...x]);setBooks(x=>x.map(b=>{const line=o.items.find(i=>i.id===b.id);return line?{...b,stock:Math.max(0,b.stock-line.qty)}:b}));(async()=>{const{error}=await supabase.from("orders").insert({id:created.id,user_id:o.userId,customer:o.customer,phone:o.phone,address:o.address,total:o.total,status:created.status});if(error){setError("تعذر حفظ الطلب: "+error.message);return}const{error:itemError}=await supabase.from("order_items").insert(o.items.map(i=>({order_id:created.id,book_id:i.id,title:i.title,quantity:i.qty,price:i.price})));if(itemError)setError("حُفظ الطلب وتعذر حفظ بعض عناصره")})();return created};
 const updateOrderStatus=(id:string,status:string)=>{setOrders(x=>x.map(o=>o.id===id?{...o,status}:o));supabase.from("orders").update({status}).eq("id",id).then(({error})=>{if(error)setError("تعذر تحديث حالة الطلب: "+error.message)})};
 const migrateLocalBooks=async()=>{const{count}=await supabase.from("books").select("id",{count:"exact",head:true});if((count||0)>0){await load();return 0}const local:Book[]=JSON.parse(localStorage.getItem("darshan-books")||"null")||seed;const rows=[];for(const b of local){let cover=b.cover;if(cover?.startsWith("data:")){const blob=await fetch(cover).then(r=>r.blob()),file=new File([blob],`cover-${Date.now()}.${blob.type.split("/")[1]||"jpg"}`,{type:blob.type});cover=await uploadBookCover(file)}rows.push(bookToDb({...b,cover}))}const{error}=await supabase.from("books").insert(rows);if(error)throw error;await load();return rows.length};
 return <C.Provider value={{books,orders,ready,cloudReady,error,addBook,updateBook,removeBook,createOrder,updateOrderStatus,migrateLocalBooks}}>{children}</C.Provider>
}
export const useStore=()=>{const x=useContext(C);if(!x)throw Error("StoreProvider missing");return x};
