"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import SiteNav from "@/components/SiteNav";
import SiteFooter from "@/components/SiteFooter";
import GoogleAuthButton from "@/components/GoogleAuthButton";
import {useAuth} from "@/lib/auth-context";
export default function Login(){const{login}=useAuth(),router=useRouter();const[notice,setNotice]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("confirmed"))setNotice("تم تأكيد بريدك بنجاح، يمكنك تسجيل الدخول الآن.");if(p.get("reset"))setNotice("تم تغيير كلمة المرور بنجاح.")},[]);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const d=Object.fromEntries(new FormData(e.currentTarget)),r=await login(String(d.email),String(d.password));setBusy(false);if(!r.ok)return setError(r.error||"");router.push("/")}return <><SiteNav/><main className="max-w-md mx-auto px-6 py-16"><div className="surface border border-line rounded-xl p-8 shadow-sm"><h1 className="text-2xl font-extrabold mb-2">تسجيل الدخول</h1><p className="text-sm text-muted mb-7">سجّل الدخول ثم تابع التسوق</p>{notice&&<div className="bg-green/10 text-green p-3 rounded mb-4 font-bold text-sm">{notice}</div>}{error&&<div className="bg-red/10 text-red p-3 rounded mb-4">{error}</div>}<GoogleAuthButton/><div className="flex items-center gap-3 my-5"><span className="h-px bg-line flex-1"/><span className="text-xs text-muted">أو باستخدام البريد</span><span className="h-px bg-line flex-1"/></div><form onSubmit={submit} className="space-y-4"><input required type="email" name="email" placeholder="البريد الإلكتروني" className="w-full border rounded p-3"/><div><input required type="password" name="password" placeholder="كلمة المرور" className="w-full border rounded p-3"/><Link href="/forgot-password" className="inline-block mt-2 text-xs text-purple font-bold">نسيت كلمة المرور؟</Link></div><button disabled={busy} className="w-full bg-purple disabled:opacity-60 text-white py-3 rounded font-bold">{busy?"جاري الدخول…":"دخول"}</button></form><p className="text-sm text-center mt-5">ليس لديك حساب؟ <Link href="/signup" className="text-purple font-bold">إنشاء حساب</Link></p></div></main><SiteFooter/></>}
